export enum CODE {
    /* COMMON */
    SUCCESS = "SUCCESS",
    ERROR = "ERROR",
    WARNING = "WARNING",
    INFO = "INFO",

    /* REQUIRED */
    REQUIRED_EMAIL = "REQUIRED_EMAIL",
    REQUIRED_ID = "REQUIRED_ID",
    REQUIRED_PASSWORD = "REQUIRED_PASSWORD",

    /* INVALID */
    INVALID_PASSWORD = "INVALID_PASSWORD",
}
