export enum CODE {
    /* COMMON */
    SUCCESS = "SUCCESS",
    FORBIDDEN = "FORBIDDEN",

    /* REQUIRED */
    REQUIRED_EMAIL = "REQUIRED_EMAIL",
    REQUIRED_ID = "REQUIRED_ID",
    REQUIRED_PASSWORD = "REQUIRED_PASSWORD",
    REQUIRED_CREDENTIAL = "REQUIRED_CREDENTIAL",

    /* INVALID */
    INVALID_PASSWORD = "INVALID_PASSWORD",
    INVALID_OLD_PASSWORD = "INVALID_OLD_PASSWORD",
}
